export const EVENT_NOTIFICATION_SSC = {
    JOIN_ROOM_NOTIFICATION_SSC: "JOIN_ROOM_NOTIFICATION_SSC",
    LEAVE_ROOM_NOTIFICATION_SSC: "LEAVE_ROOM_NOTIFICATION_SSC",
    SEND_NOTIFICATION_SSC: "SEND_NOTIFICATION_SSC"
}
